name: pick_lowdim

obs_dim: 15
action_dim: 4
keypoint_dim: 7

env_runner:
  _target_: diffusion_policy.env_runner.pick_place_env_runner.PickPlaceEnvRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 10
  agent_keypoints: False
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.pick_place_dataset.PickPlaceLowdimDataset
  zarr_path: data/demo_seed_1/2_split_keypoint/pick/keypoint/keypoint.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
